on: 
  push:
    branches:
      - master

name: Build and publish site
jobs:
  build-bundle-deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download data
        run: python3 get_data.py /tmp/data.jsonl

      - name: Compile site
        run: python3 build_site.py /tmp/data.jsonl

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: site
          fqdn: as-stats.ewpratten.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}